### ISSUE TITLE
Ring buffer updates lack memory barriers

### ISSUE THREAD

**Issue by badgerious** [Microsemi/switchtec-dma#4]
The producer and consumer of the swdma_chan ring buffer do not perform updates under a common lock (`complete_lock` vs. `submit_lock`). The head/tail updates are therefore risking races. The scheme described in Documentation/core-api/circular-buffers.rst appears required here to guarantee correct behavior.

**Comment by kelvin-cao** [comment]
Thank you for pointing this out. I'll take a closer look.

Kelvin

**Comment by kelvin-cao** [comment]
Sorry for the delay. I should have placed memory barriers when I switch to current two locks mechanism for performance improvement. It seems PR#3 is fixing one of the error phenomenon that we can see with this issue. I'd prefer to resolve this first and then see what we can do with 'completed'. I'll also add other patches to ensure ordering and prevent compiler and CPU optimizations. 

Kelvin

**Comment by kelvin-cao** [comment]
Hi @badgerious, I've come up with a fix in PR #5.

**Comment by badgerious** [comment]
Great, thanks. Since the `head++` in `switchtec_dma_prep_desc()` has moved until after `desc->completed = false`, #3 is probably resolved by #5. That said, I'm afraid I no longer have access to the hardware or documentation (due to change of employer), so I won't be able to do any testing.

**Comment by kelvin-cao** [comment]
Thanks for taking a look at the code and share what you observed. I can do the test you did if you can describe a bit about it. 

Congrats!

**Comment by badgerious** [comment]
Cheers, thanks.

Most of the testing I did was (non-public) application tests, but the gist is simple: send a flood of DMA requests right after module load (such that all descriptors have their initial state, i.e, `desc->completed == true`). I found that I hit the dma_cookie_complete() BUG_ON() about 50% of such tests.

**Comment by kelvin-cao** [comment]
I failed reproduce this issue on my platform with a test client sending DMA requests flood. However, when I added some delay between `swdma_chan->head++;` and `desc->completed = false`, then I can very easily hit the dma_cookie_complete() BUG_ON(). So I believe PR#5 is the fix for this issue.
